repository.go
repository_test.go

Add Maven repository data and test job for group data

Add Maven repository data

---

blobstore.go
blobstore_test.go
client.go

Add structs and methods to manage blobstores

Support Blobstores

---

client.go
privilege.go
privilege_test.go

This adds support for privileges with the intent of adding support to the terraform provider.

Add support for Privileges

---

client.go
content_selector.go
content_selector_test.go

This just adds support for content selectors with the intent to pull this into the terraform provider.

Add support for Content Selectors

---

blobstore_test.go
repository.go
repository_test.go
scripts/start-nexus.sh

- use go-nexus-client v0.8.1
- refactored scripts/start-nexus.sh in order to quickly change port
- changed API call from maven2 to maven

enable maven

---

repository.go
repository_apt.go
repository_apt_test.go
repository_bower_test.go
repository_docker_test.go
repository_maven_test.go
repository_nuget_test.go
repository_pypi_test.go

Optional proxy repository HTTP client authentication and add parameter flag to Apt proxy

Optional proxy auth and Apt proxy parameter flag

---

repository.go
repository_yum.go

Adding yum format support

---

certificate.go
certificate_test.go
client.go
go.mod
go.sum

Implementation of certificates REST API

Adding certificate API

---

client.go
user_token.go
user_token_test.go

Add support for updating user token configuration

---

.github/dependabot.yml
.github/workflows/codeql-analysis.yml
.github/workflows/feature-branches.yaml
README.md

So that we get an insight of what we should / must improve!
Dependabot to automatically create package upgrade pull requests.

chore(.github): enabled codeql-analysis and updated workflow, dependabot

---

nexus3/pkg/blobstore/azure_test.go
nexus3/pkg/blobstore/group_test.go
nexus3/pkg/security/role.go

for issue: https://github.com/datadrivers/terraform-provider-nexus/issues/139

feat(role): Improve function Get of role service

---

nexus3/pkg/repository/common/common.go
nexus3/pkg/repository/service.go
nexus3/pkg/repository/service_test.go
nexus3/schema/repository/repository.go

For issue: https://github.com/datadrivers/terraform-provider-nexus/issues/69

feat(repository): Add function List to repository service

---

nexus3/pkg/repository/apt/hosted_test.go
nexus3/pkg/repository/legacy/apt_test.go
nexus3/schema/repository/apt.go

Correction of the marking as required for distribution and keypair in apt schema

fix(repository): Correction of the marking as required

---

nexus3/pkg/repository/bower/proxy_test.go
nexus3/schema/repository/bower.go

fix(bower): Remove pointer for bower struct in BowerProxy struct

---

nexus3/pkg/security/role.go

Аdded escape of role id variable
https://github.com/datadrivers/go-nexus-client/issues/101

escape url variables

---

.github/workflows/feature-branches.yaml
CODE_OF_CONDUCT.md
README.md
go.mod
go.sum
scripts/.env

additional: 
- Add Code of Conduct

feat:  Update golang version, dependencies and nexus3 version

---

.github/workflows/feature-branches.yaml
.pre-commit-config.yaml

ci: Activate pro features tests in ci with new licence

---

nexus3/pkg/repository/docker/docker_proxy_test.go
nexus3/schema/repository/docker.go

related to https://github.com/datadrivers/terraform-provider-nexus/issues/109

feat: Add support for foreign layer caching

---

nexus3/pkg/security/user.go
nexus3/pkg/security/user_test.go

This PR adds the capability to specify the source when querying for a user.

feat: add source to get user function

---

nexus3/pkg/repository/cargo/group.go
nexus3/pkg/repository/cargo/group_test.go
nexus3/pkg/repository/cargo/hosted.go
nexus3/pkg/repository/cargo/hosted_test.go
nexus3/pkg/repository/cargo/proxy.go
nexus3/pkg/repository/cargo/proxy_test.go
nexus3/pkg/repository/cargo/service.go
nexus3/pkg/repository/cargo/service_test.go
nexus3/pkg/repository/service.go
nexus3/schema/repository/cargo.go

support Rust `cargo` repository

---

nexus3/pkg/security/saml_test.go
nexus3/schema/security/saml.go

related to https://github.com/datadrivers/terraform-provider-nexus/issues/501

fix: Fix default handling in saml client

---

nexus3/pkg/repository/npm/proxy_test.go
nexus3/schema/repository/http_client.go

related to: https://github.com/datadrivers/terraform-provider-nexus/issues/158

feat: add bearerToken auth to npm proxy
